alias mbr="mvn blade:run"
alias mcidb!="mvn clean install -Pclean-database"
alias mbbp="mvn bb:provision"
alias mbbi="mvn bb:import-experiences"
alias mcisat="mvn clean install -Dskip.unit.tests -Dskip.integration.tests"